version: '3.8'

services:
  rasa:
    build: 
      context: ./rasa_bot
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./rasa_bot:/app
    environment:
      - PYTHONPATH=/app
      - RASA_ACTIONS_URL=http://rasa-actions:5055/webhook
    command: run -m http://0.0.0.0:5005 --endpoints endpoints.yml
    depends_on:
      - rasa-actions
      - db
      - kafka

  rasa-actions:
    build:
      context: ./rasa_bot
      dockerfile: actions.Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - ./rasa_bot/actions:/app/actions
    environment:
      - PYTHONPATH=/app
      - BACKEND_URL=http://backend:8000
    command: ["rasa", "run", "actions", "--actions", "actions"]

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - SMS_API_KEY=${SMS_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: